import {
    FaUser,
    FaShoppingCart,
    FaSearch,
    FaLongArrowAltRight,
    FaGithub,
    FaFacebook,
    FaLinkedin,
    FaChevronCircleUp,
    FaEnvelope,
    FaPhoneAlt,
    FaTrashAlt,
    FaArchive,
    FaTruck,
    FaClock,
    FaSnowplow,
    FaSnowman,
} from "react-icons/fa";
const Icons = {
    FaUser,
    FaShoppingCart,
    FaSearch,
    FaLongArrowAltRight,
    FaGithub,
    FaFacebook,
    FaLinkedin,
    FaChevronCircleUp,
    FaEnvelope,
    FaPhoneAlt,
    FaTrashAlt,
    FaArchive,
    FaTruck,
    FaClock,
    FaSnowplow,
    FaSnowman,
};

export default Icons;
